package com.entitys;
// Generated 6/11/2016 11:42:32 PM by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private String telefonoArea;
     private Usuarios usuarios;
     private String telefono;
     private String codigoArea;
     private String codigoConfirm;
     private String status;

    public Telefonos() {
    }

	
    public Telefonos(String telefonoArea, Usuarios usuarios, String telefono, String codigoArea) {
        this.telefonoArea = telefonoArea;
        this.usuarios = usuarios;
        this.telefono = telefono;
        this.codigoArea = codigoArea;
    }
    public Telefonos(String telefonoArea, Usuarios usuarios, String telefono, String codigoArea, String codigoConfirm, String status) {
       this.telefonoArea = telefonoArea;
       this.usuarios = usuarios;
       this.telefono = telefono;
       this.codigoArea = codigoArea;
       this.codigoConfirm = codigoConfirm;
       this.status = status;
    }
   
    public String getTelefonoArea() {
        return this.telefonoArea;
    }
    
    public void setTelefonoArea(String telefonoArea) {
        this.telefonoArea = telefonoArea;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public String getCodigoConfirm() {
        return this.codigoConfirm;
    }
    
    public void setCodigoConfirm(String codigoConfirm) {
        this.codigoConfirm = codigoConfirm;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


